load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["assert.go"],
    importpath = "github.com/marpaia/quanto/internal/assert",
    visibility = ["//:__subpackages__"],
)
