version: 2
jobs:
  build:
    docker:
      - image: l.gcr.io/google/bazel:0.21.0
    working_directory: /math-go
    steps: &steps
      - checkout
      - run: bazel build ...
      - run: bazel test ...
workflows:
  version: 2
  build:
    jobs:
      - build
